import { CompleteEventType, MonthAllEventsType } from '@/types/hiStory';

import { EventDetailType } from '@/pages/hi-story/completed-events/[eventId]';

export const mockCompletedEventList: CompleteEventType[] = [
  {
    eventId: 1,
    title: '예소 중간발표!',
    category: '프로젝트',
    // memo: '떨린다 발표~~',
    eventStatus: 'termination',
    startDate: '2024-05-30',
    endDate: '2024-07-10',
    fileUrl: '/image/dummy/love_flower.png',
    emotion: 'LOVE',
    totalQuestionCount: 21,
    totalAnswerCount: 21,
    representativeQuestion: {
      questionId: 302,
      content: '중간발표를 통해 얻은 가장 큰 교훈은?',
      isPriority: true,
      isAnswer: true,
      myAnswer: '팀워크의 중요성과 효과적인 커뮤니케이션 스킬을 배웠습니다.',
      questionDate: '2024-07-10',
      answeredAt: '2024-07-10',
      fileUrl: 'https://example.com/presentation-learnings.jpg',
      type: 'IMAGE',
      eventTitle: '예소 중간발표!',
    },
  },
  {
    eventId: 2,
    title: '팀 d!no 회식🌼',
    category: '팀빌딩',
    memo: '우리팀 첫 회식..!',
    eventStatus: 'termination',
    startDate: '2024-06-11',
    endDate: '2024-06-18',
    fileUrl: '/image/dummy/expectation_flower.png',
    emotion: 'EXPECTATION',
    totalQuestionCount: 8,
    totalAnswerCount: 8,
    representativeQuestion: {
      questionId: 303,
      content: '회식을 통해 팀원들과 더 가까워진 것 같나요?',
      isPriority: false,
      isAnswer: true,
      myAnswer: '네, 편안한 분위기에서 서로를 더 잘 이해하게 되었습니다.',
      questionDate: '2024-06-18',
      answeredAt: '2024-06-18',
      fileUrl: 'https://example.com/team-bonding-audio.mp3',
      type: 'VOICE',
      eventTitle: '팀 d!no 회식🌼',
    },
  },
  {
    eventId: 3,
    title: '예소 네트워킹 데이',
    category: '네트워킹',
    memo: '두번째 예소, 두번째 네트워킹!',
    eventStatus: 'termination',
    startDate: '2024-04-15',
    endDate: '2024-05-03',
    fileUrl: '/image/dummy/hope_flower.png',
    emotion: 'HOPE',
    totalQuestionCount: 7,
    totalAnswerCount: 7,
    representativeQuestion: {
      questionId: 301,
      content: '네트워킹 이벤트에서 가장 인상 깊었던 만남은?',
      isPriority: false,
      isAnswer: true,
      myAnswer: '다양한 분야의 전문가들과 소통할 수 있어 매우 유익했습니다.',
      questionDate: '2024-05-03',
      answeredAt: '2024-05-03',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '예소 네트워킹데이',
    },
  },
];

export const mockEventDetailList: EventDetailType[] = [
  {
    eventId: 1,
    title: '완료된 첫 번째 이벤트',
    emotion: '행복',
    eventStatus: 'termination',
    startDate: '2023-09-01',
    endDate: '2023-09-01',
    memo: '일상의 소중함을 깨달은 하루',
    fileUrl: 'https://example.com/event1.jpg',
    totalQuestionCount: 3,
    totalAnswerCount: 3,
    occurrenceTime: '09:00',
    representativeQuestion: {
      questionId: 201,
      content: '이벤트를 통해 무엇을 배웠나요?',
      isAnswer: true,
      myAnswer: '새로운 경험의 중요성을 깨달았습니다.',
      answeredAt: '2023-09-01',
      isPriority: true,
      questionDate: '2023-09-01',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '완료된 첫 번째 이벤트',
    },
    questionContent: [
      {
        questionId: 201,
        content: '이벤트를 통해 무엇을 배웠나요?',
        isAnswer: true,
        myAnswer: '새로운 경험의 중요성을 깨달았습니다.',
        answeredAt: '2023-09-01',
        isPriority: true,
        questionDate: '2023-09-01',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '완료된 첫 번째 이벤트',
      },
      {
        questionId: 202,
        content: '오늘 하루 중 가장 기억에 남는 순간은?',
        isAnswer: true,
        myAnswer: '가족과 함께한 저녁 식사 시간이었습니다.',
        answeredAt: '2023-09-01',
        isPriority: false,
        questionDate: '2023-09-01',
        fileUrl: 'https://example.com/family-dinner.jpg',
        type: 'IMAGE',
        eventTitle: '완료된 첫 번째 이벤트',
      },
    ],
  },
  {
    eventId: 2,
    title: '완료된 두 번째 이벤트',
    emotion: '설렘',
    eventStatus: 'termination',
    startDate: '2023-09-02',
    endDate: '2023-09-03',
    memo: '잊지 못할 주말 여행',
    fileUrl: 'https://example.com/event2.jpg',
    totalQuestionCount: 2,
    totalAnswerCount: 2,
    occurrenceTime: '10:30',
    representativeQuestion: {
      questionId: 203,
      content: '가장 인상 깊었던 순간은?',
      isAnswer: true,
      myAnswer: '석양을 바라보며 느낀 평화로움이었습니다.',
      answeredAt: '2023-09-02',
      isPriority: true,
      questionDate: '2023-09-02',
      fileUrl: 'https://example.com/sunset.jpg',
      type: 'IMAGE',
      eventTitle: '완료된 두 번째 이벤트',
    },
    questionContent: [
      {
        questionId: 203,
        content: '가장 인상 깊었던 순간은?',
        isAnswer: true,
        myAnswer: '석양을 바라보며 느낀 평화로움이었습니다.',
        answeredAt: '2023-09-02',
        isPriority: true,
        questionDate: '2023-09-02',
        fileUrl: 'https://example.com/sunset.jpg',
        type: 'IMAGE',
        eventTitle: '완료된 두 번째 이벤트',
      },
      {
        questionId: 204,
        content: '이번 여행에서 새롭게 시도해본 것이 있다면?',
        isAnswer: true,
        myAnswer: '현지 요리 수업에 참여해 전통 음식을 만들어 보았습니다.',
        answeredAt: '2023-09-03',
        isPriority: false,
        questionDate: '2023-09-03',
        fileUrl: 'https://example.com/cooking-class.mp3',
        type: 'VOICE',
        eventTitle: '완료된 두 번째 이벤트',
      },
    ],
  },
  {
    eventId: 3,
    title: '완료된 세 번째 이벤트',
    emotion: '호기심',
    eventStatus: 'termination',
    startDate: '2023-09-04',
    endDate: '2023-09-04',
    memo: '새로운 지식의 발견',
    fileUrl: 'https://example.com/event3.jpg',
    totalQuestionCount: 1,
    totalAnswerCount: 1,
    occurrenceTime: '14:00',
    representativeQuestion: {
      questionId: 205,
      content: '새롭게 알게 된 사실이 있나요?',
      isAnswer: true,
      myAnswer: '인공지능의 윤리적 측면에 대해 깊이 있게 배웠습니다.',
      answeredAt: '2023-09-04',
      isPriority: true,
      questionDate: '2023-09-04',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '완료된 세 번째 이벤트',
    },
    questionContent: [
      {
        questionId: 205,
        content: '새롭게 알게 된 사실이 있나요?',
        isAnswer: true,
        myAnswer: '인공지능의 윤리적 측면에 대해 깊이 있게 배웠습니다.',
        answeredAt: '2023-09-04',
        isPriority: true,
        questionDate: '2023-09-04',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '완료된 세 번째 이벤트',
      },
    ],
  },
];

const eventTitles = [
  '완료된 첫 번째 이벤트',
  '완료된 두 번째 이벤트',
  '완료된 세 번째 이벤트',
  '예술적인소프트웨어 대회',
  '30일 건강 챌린지',
  '연말 자선 봉사활동',
];

const getRandomEventTitle = () => {
  return eventTitles[Math.floor(Math.random() * eventTitles.length)];
};

export const mockAllEventList: MonthAllEventsType[] = [
  {
    groupByDate: '2023-09',
    questionContent: [
      {
        questionId: 101,
        content: '오늘의 기분은 어떤가요?',
        isAnswer: true,
        myAnswer: '매우 좋습니다!',
        isPriority: true,
        questionDate: '2023-09-15',
        answeredAt: '2023-09-15',
        fileUrl: 'https://example.com/image1.jpg',
        type: 'TEXT',
        eventTitle: getRandomEventTitle(),
      },
      {
        questionId: 102,
        content: '가장 기억에 남는 순간은?',
        isAnswer: false,
        myAnswer: '',
        isPriority: false,
        questionDate: '2023-09-20',
        answeredAt: '',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: getRandomEventTitle(),
      },
    ],
  },
  {
    groupByDate: '2023-08',
    questionContent: [
      {
        questionId: 103,
        content: '오늘의 목표를 말해보세요.',
        isAnswer: true,
        myAnswer: 'voice_answer.mp3',
        isPriority: true,
        questionDate: '2023-08-10',
        answeredAt: '2023-08-10',
        fileUrl: 'https://example.com/voice_answer.mp3',
        type: 'VOICE',
        eventTitle: getRandomEventTitle(),
      },
    ],
  },
  {
    groupByDate: '2023-07',
    questionContent: [
      {
        questionId: 104,
        content: '오늘의 순간을 사진으로 남겨주세요.',
        isAnswer: true,
        myAnswer: 'today_photo.jpg',
        isPriority: false,
        questionDate: '2023-07-05',
        answeredAt: '2023-07-05',
        fileUrl: 'https://example.com/today_photo.jpg',
        type: 'IMAGE',
        eventTitle: getRandomEventTitle(),
      },
      {
        questionId: 105,
        content: '이번 여름 휴가 계획은 무엇인가요?',
        isAnswer: true,
        myAnswer: '제주도로 가족 여행을 갈 예정입니다.',
        isPriority: true,
        questionDate: '2023-07-10',
        answeredAt: '2023-07-10',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: getRandomEventTitle(),
      },
      {
        questionId: 106,
        content: '최근에 시작한 새로운 취미가 있나요?',
        isAnswer: true,
        myAnswer: '요가를 시작했어요. 매일 아침 30분씩 하고 있습니다.',
        isPriority: false,
        questionDate: '2023-07-15',
        answeredAt: '2023-07-15',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: getRandomEventTitle(),
      },
      {
        questionId: 107,
        content: '가장 좋아하는 여름 음식은 무엇인가요?',
        isAnswer: true,
        myAnswer: '시원한 물냉면이요. 특히 더운 날 먹으면 정말 좋아요.',
        isPriority: false,
        questionDate: '2023-07-20',
        answeredAt: '2023-07-20',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: getRandomEventTitle(),
      },
      {
        questionId: 108,
        content: '이번 여름에 자주 듣는 노래는?',
        isAnswer: true,
        myAnswer: 'summer.mp3',
        isPriority: false,
        questionDate: '2023-07-25',
        answeredAt: '2023-07-25',
        fileUrl: 'https://example.com/summer.mp3',
        type: 'VOICE',
        eventTitle: getRandomEventTitle(),
      },
    ],
  },
  {
    groupByDate: '2023-06',
    questionContent: [
      {
        questionId: 109,
        content: '이번 달의 개인적인 목표는 무엇인가요?',
        isAnswer: true,
        myAnswer: '매일 30분 이상 책 읽기',
        isPriority: true,
        questionDate: '2023-06-01',
        answeredAt: '2023-06-01',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: getRandomEventTitle(),
      },
      {
        questionId: 110,
        content: '요즘 자주 가는 좋아하는 장소가 있나요?',
        isAnswer: true,
        myAnswer: 'favorite_place.jpg',
        isPriority: false,
        questionDate: '2023-06-10',
        answeredAt: '2023-06-10',
        fileUrl: 'https://example.com/favorite_place.jpg',
        type: 'IMAGE',
        eventTitle: getRandomEventTitle(),
      },
      {
        questionId: 111,
        content: '최근에 시도해 본 새로운 것이 있다면?',
        isAnswer: true,
        myAnswer:
          '베이킹을 처음 해봤어요. 쿠키를 만들었는데 생각보다 맛있었습니다!',
        isPriority: false,
        questionDate: '2023-06-15',
        answeredAt: '2023-06-15',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: getRandomEventTitle(),
      },
      {
        questionId: 112,
        content: '오늘 하루 동안 감사했던 순간은?',
        isAnswer: true,
        myAnswer: '동료가 어려운 업무를 도와줘서 정말 고마웠어요.',
        isPriority: true,
        questionDate: '2023-06-20',
        answeredAt: '2023-06-20',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: getRandomEventTitle(),
      },
    ],
  },
];
