import { CompleteEventType, MonthAllEventsType } from '@/types/hiStory';

import { EventDetailType } from '@/pages/hi-story/completed-events/[eventId]';

export const mockCompletedEventList: CompleteEventType[] = [
  {
    eventId: 1,
    title: '예소 중간발표!',
    category: '프로젝트',
    eventStatus: 'termination',
    startDate: '2024-05-30',
    endDate: '2024-07-10',
    fileUrl: '/image/dummy/love_flower.png',
    emotion: 'LOVE',
    totalQuestionCount: 21,
    totalAnswerCount: 21,
    representativeQuestion: {
      questionId: 218,
      content: '발표 준비 과정에서 가장 기억에 남는 에피소드는 무엇인가요?',
      isAnswer: true,
      myAnswer:
        '첫 회의 때 의견 충돌 있었는데 그러다가 오히려 더 좋은 아이디어가 나왔던 거요, 지금 생각하면 그게 제일 기억에 남아요.',
      answeredAt: '2024-07-04',
      isPriority: false,
      questionDate: '2024-07-04',
      fileUrl:
        'https://daydreamcdn.s3.ap-northeast-2.amazonaws.com/DayDream/dummy/KakaoTalk_Photo_2024-10-04-01-10-27.jpeg',
      type: 'IMAGE',
      eventTitle: '예소 중간발표!',
    },
  },
  {
    eventId: 2,
    title: '팀 d!no 회식🌼',
    category: '팀빌딩',
    memo: '우리팀 첫 회식..!',
    eventStatus: 'termination',
    startDate: '2024-06-11',
    endDate: '2024-06-18',
    fileUrl: '/image/dummy/expectation_flower.png',
    emotion: 'EXPECTATION',
    totalQuestionCount: 8,
    totalAnswerCount: 8,
    representativeQuestion: {
      questionId: 303,
      content:
        '이 자리가 여러분의 마음속에 어떤 행복한 기억으로 남길 바라는가요?',
      isPriority: false,
      isAnswer: true,
      myAnswer:
        '다 같이 웃고 떠들면서 술 마시던 그 순간들이 오래오래 기억에 남았으면 좋겠어요!',
      questionDate: '2024-06-18',
      answeredAt: '2024-06-18',
      fileUrl: 'https://example.com/team-bonding-audio.mp3',
      type: 'TEXT',
      eventTitle: '팀 d!no 회식🌼',
    },
  },
  {
    eventId: 3,
    title: '예소 네트워킹 데이',
    category: '네트워킹',
    memo: '두번째 예소, 두번째 네트워킹!',
    eventStatus: 'termination',
    startDate: '2024-04-15',
    endDate: '2024-05-03',
    fileUrl: '/image/dummy/hope_flower.png',
    emotion: 'HOPE',
    totalQuestionCount: 7,
    totalAnswerCount: 7,
    representativeQuestion: {
      questionId: 403,
      content:
        '이번 네트워킹에서 나누는 대화가 당신에게 어떤 긍정적인 변화를 가져올 것이라 생각하나요?',
      isAnswer: true,
      myAnswer:
        '아무래도 컴공과 사람들이랑 얘기하다 보면 기술적인 부분 이해도 늘고 협업 능력도 좋아질 것 같아요, 진짜 기대돼요!',
      answeredAt: '2024-04-21',
      isPriority: false,
      questionDate: '2024-04-21',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '예소 네트워킹 데이',
    },
  },
];

export const mockEventDetailList: EventDetailType[] = [
  {
    eventId: 1,
    title: '예소 중간발표!',
    emotion: 'LOVE',
    eventStatus: 'termination',
    startDate: '2024-05-30',
    endDate: '2024-07-10',
    memo: '우리 팀의 첫 중간발표!',
    fileUrl: '/image/dummy/love_flower.png',
    totalQuestionCount: 21,
    totalAnswerCount: 21,
    occurrenceTime: '09:00',
    representativeQuestion: {
      questionId: 218,
      content: '발표 준비 과정에서 가장 기억에 남는 에피소드는 무엇인가요?',
      isAnswer: true,
      myAnswer:
        '첫 회의 때 의견 충돌 있었는데 그러다가 오히려 더 좋은 아이디어가 나왔던 거요, 지금 생각하면 그게 제일 기억에 남아요.',
      answeredAt: '2024-07-04',
      isPriority: false,
      questionDate: '2024-07-04',
      fileUrl:
        'https://daydreamcdn.s3.ap-northeast-2.amazonaws.com/DayDream/dummy/KakaoTalk_Photo_2024-10-04-01-10-27.jpeg',
      type: 'IMAGE',
      eventTitle: '예소 중간발표!',
    },
    questionContent: [
      {
        questionId: 201,
        content: '이번 중간 발표에서 가장 기대하고 있는 부분은 어떤 건가요?',
        isAnswer: true,
        myAnswer:
          '다른 팀들이 어떤 주제로 프로젝트 하는지 너무 궁금해요, 우리 아이디어랑 비교해보고 싶어요!',
        answeredAt: '2024-05-30',
        isPriority: true,
        questionDate: '2024-05-30',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 202,
        content: '발표를 통해 전하고 싶은 메시지는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '우리 팀이 고민한 주제의 중요성이랑 의미가 잘 전달됐으면 좋겠어요, 특히 기다림에 대한 예술적 표현이랑 그걸 기술적으로 융합한 부분요.',
        answeredAt: '2024-06-01',
        isPriority: false,
        questionDate: '2024-06-01',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 203,
        content: '중간 발표를 통해 어떤 피드백을 받고 싶으신가요?',
        isAnswer: true,
        myAnswer:
          '교수님들이 우리 아이디어 방향성에 대해 조언 좀 해주셨으면 좋겠어요, 아직 초기 단계라 도움이 필요해요.',
        answeredAt: '2024-06-03',
        isPriority: false,
        questionDate: '2024-06-03',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 204,
        content: '발표 전 준비하면서 가장 설렜던 순간은 언제였나요?',
        isAnswer: true,
        myAnswer:
          '팀원들이랑 처음으로 아이디어 회의할 때였어요. 다들 열정적으로 의견 내는 모습 보고 앞으로의 프로젝트가 어떨지 설렜어요!',
        answeredAt: '2024-06-05',
        isPriority: false,
        questionDate: '2024-06-05',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 205,
        content:
          '이번 중간 발표에서 팀원들과의 협력이 어떤 의미를 가지길 바라나요?',
        isAnswer: true,
        myAnswer:
          '컴공과랑 디자인과가 만나서 서로 다른 시각으로 문제 해결하는 게 잘 드러났으면 좋겠어요.',
        answeredAt: '2024-06-07',
        isPriority: false,
        questionDate: '2024-06-07',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 206,
        content: '발표 후 어떤 성취감을 느끼고 싶으신가요?',
        isAnswer: true,
        myAnswer:
          '우리 아이디어가 다른 팀들이나 교수님들께 좋은 인상을 남겼으면 좋겠어요. 주제에 대해 고민을 많이 했는데 그것에 대한 좋은 평가를 받고 싶어요!',
        answeredAt: '2024-06-09',
        isPriority: false,
        questionDate: '2024-06-09',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 207,
        content: '이 아이디어에 대한 남다른 열정을 느끼는 순간은 언제인가요?',
        isAnswer: true,
        myAnswer:
          '밤늦게까지 아이디어 회의하다가 갑자기 와, 이거 진짜 대박일 수도? 하는 생각이 들 때 열정 불타요.',
        answeredAt: '2024-06-11',
        isPriority: false,
        questionDate: '2024-06-11',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 208,
        content: '중간 발표에서 청중의 반응을 어떻게 느끼길 기대하나요?',
        isAnswer: true,
        myAnswer:
          '발표할 때 다른 팀들이 우리 아이디어에 관심 보이면서 질문 많이 해줬으면 좋겠어요!',
        answeredAt: '2024-06-13',
        isPriority: false,
        questionDate: '2024-06-13',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 209,
        content:
          '이번 발표 때문에 밤잠을 설쳐본 경험이 있다면 그건 어떤 기분이었나요?',
        isAnswer: true,
        myAnswer:
          '비대면이라 긴장은 덜 한데, 그래도 잘 전달될까 걱정되는 마음에 좀 설레요.',
        answeredAt: '2024-06-15',
        isPriority: false,
        questionDate: '2024-06-15',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 210,
        content: '발표가 끝난 후 가장 먼저 하고 싶은 일은 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '팀원들이랑 화상으로 모여서 치맥하면서 수고했다고 말해주고 싶어요, 다들 아이디어 내느라 고생했거든요.',
        answeredAt: '2024-06-17',
        isPriority: false,
        questionDate: '2024-06-17',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 211,
        content:
          '이 아이디어가 더 많은 사람에게 알려졌으면 하는 이유는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '우리 아이디어가 간단하면서도 재미있는 부분을 담고 있어서 이런 재미있는 접근을 하고 있다는 것을 알아줬으면 좋겠어요!',
        answeredAt: '2024-06-20',
        isPriority: false,
        questionDate: '2024-06-20',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 212,
        content: '중간 발표가 끝났을 때, 어떤 마음으로 돌아가고 싶으신가요?',
        isAnswer: true,
        myAnswer:
          '뿌듯하고 기대되는 마음으로 발표 끝나고 싶어요, 앞으로 어떻게 발전시킬지 생각하면서요.',
        answeredAt: '2024-06-22',
        isPriority: false,
        questionDate: '2024-06-22',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 213,
        content:
          '발표를 준비하면서 느낀 긴장감은 어떤 형태로 표현할 수 있을까요?',
        isAnswer: true,
        myAnswer:
          '약간 첫 소개팅 나가기 전 같은 느낌? 설레면서도 잘 할 수 있을지 걱정되는 그런 느낌이에요.',
        answeredAt: '2024-06-24',
        isPriority: false,
        questionDate: '2024-06-24',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 214,
        content: '발표에서 가장 자랑스럽게 생각하는 부분은 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '우리가 밤새 고민해서 만든 아이디어의 독창성이요, 그 부분 자랑하고 싶어요.',
        answeredAt: '2024-06-26',
        isPriority: false,
        questionDate: '2024-06-26',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 215,
        content:
          '이번 중간 발표가 끝난 후, 다시 하고 싶은 일이 있다면 어떤 건가요?',
        isAnswer: true,
        myAnswer:
          '발표 끝나고 나서 팀원들이랑 다시 모여서 다른 팀 아이디어랑 비교해보고 우리 것도 더 발전시키고 싶어요.',
        answeredAt: '2024-06-28',
        isPriority: false,
        questionDate: '2024-06-28',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 216,
        content: '발표를 통해 나의 성장과 변화를 느끼길 바라나요?',
        isAnswer: true,
        myAnswer:
          '이번 기회로 아이디어 구체화하는 능력이랑 발표 스킬도 늘었으면 좋겠어요. 그리고 소융대랑 같이 하는 만큼, 기술적인 부분에서 이해도가 높아지길 기대하고 있어요.',
        answeredAt: '2024-06-30',
        isPriority: false,
        questionDate: '2024-06-30',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 217,
        content:
          '중간 발표를 통해 더 크게 도약할 수 있을 것 같은 순간은 어떤 때인가요?',
        isAnswer: true,
        myAnswer:
          '발표 끝나고 교수님들이 우리 아이디어에 조언해주실 때요, 그때 진짜 프로젝트가 더 발전할 수 있을 것 같아요.',
        answeredAt: '2024-07-02',
        isPriority: false,
        questionDate: '2024-07-02',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 218,
        content: '발표 준비 과정에서 가장 기억에 남는 에피소드는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '첫 회의 때 의견 충돌 있었는데 그러다가 오히려 더 좋은 아이디어가 나왔던 거요, 지금 생각하면 그게 제일 기억에 남아요.',
        answeredAt: '2024-07-04',
        isPriority: false,
        questionDate: '2024-07-04',
        fileUrl:
          'https://daydreamcdn.s3.ap-northeast-2.amazonaws.com/DayDream/dummy/KakaoTalk_Photo_2024-10-04-01-10-27.jpeg',
        type: 'IMAGE',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 219,
        content: '이 아이디어에 대한 사랑이 더욱 깊어지는 순간은 언제인가요?',
        isAnswer: true,
        myAnswer:
          '우리 아이디어로 실제로 누군가의 삶이 더 즐거워질 수 있겠다고 생각할 때마다 더 애착이 가요.',
        answeredAt: '2024-07-06',
        isPriority: false,
        questionDate: '2024-07-06',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 220,
        content: '발표 직후 느낄 화려한 감정은 어떤 모습일까요?',
        isAnswer: true,
        myAnswer:
          '아마 뿌듯하면서도 약간은 안도감이 들 것 같아요, 첫 관문 통과한 느낌?',
        answeredAt: '2024-07-08',
        isPriority: false,
        questionDate: '2024-07-08',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 221,
        content:
          '이번 중간 발표가 끝난 후 가장 큰 기대감으로 남을 것은 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '이번 중간 발표를 통해 받은 피드백으로 우리 아이디어를 더 발전시켜서 최종 발표 때 수상을 할 수 있지 않을까 하는 기대감이요!',
        answeredAt: '2024-07-10',
        isPriority: false,
        questionDate: '2024-07-10',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
    ],
  },
  {
    eventId: 2,
    title: '팀 d!no 회식🌼',
    emotion: 'EXPECTATION',
    eventStatus: 'termination',
    startDate: '2024-06-11',
    endDate: '2024-06-18',
    memo: '우리팀 첫 회식..!',
    fileUrl: '/image/dummy/expectation_flower.png',
    totalQuestionCount: 8,
    totalAnswerCount: 8,
    occurrenceTime: '19:00',
    representativeQuestion: {
      questionId: 303,
      content:
        '이 자리가 여러분의 마음속에 어떤 행복한 기억으로 남길 바라는가요?',
      isPriority: false,
      isAnswer: true,
      myAnswer:
        '다 같이 웃고 떠들면서 술 마시던 그 순간들이 오래오래 기억에 남았으면 좋겠어요!',
      questionDate: '2024-06-18',
      answeredAt: '2024-06-18',
      fileUrl: 'https://example.com/team-bonding-audio.mp3',
      type: 'TEXT',
      eventTitle: '팀 d!no 회식🌼',
    },
    questionContent: [
      {
        questionId: 301,
        content: '이번 회식에서 어떤 특별한 순간을 기대하고 있나요?',
        isAnswer: true,
        myAnswer:
          '아, 진짜 기대되는 건 선배들이랑 처음으로 술 마시는 거? 엄청 떨리긴 한데 재밌을 것 같아요!',
        answeredAt: '2024-06-11',
        isPriority: true,
        questionDate: '2024-06-11',
        fileUrl: 'https://example.com/team-dinner-expectations.jpg',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 302,
        content:
          '팀원들과 나누고 싶은 가장 재밌는 이야기나 에피소드는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '음...술 마시는 자리니까 술 마시고 생긴 웃긴얘기를 풀면 될 것 같아요. 그냥 제가 MT 갔다가 술 마시고 화장실 못 찾아서 헤맨 얘기 하면 다들 웃겠죠?',
        answeredAt: '2024-06-12',
        isPriority: false,
        questionDate: '2024-06-12',
        fileUrl: 'https://example.com/funny-story-audio.mp3',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 303,
        content: '회식에서 어떤 음식을 가장 기대하고 있나요?',
        isAnswer: true,
        myAnswer:
          '진짜 삼겹살이랑 소주 콤보가 최고인 것 같아요, 근데 회식이라 좀 비싼 거 먹을 수 있을까 봐 기대돼요!',
        answeredAt: '2024-06-13',
        isPriority: false,
        questionDate: '2024-06-13',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 304,
        content:
          '팀원들과의 첫 만남 이후 서로에 대한 인상이 어떻게 바뀌었나요?',
        isAnswer: true,
        myAnswer:
          '아무래도 술 마시고 얘기 많이 하면 더 친해질 것 같은데... 제가 실수하면 어쩌죠?',
        answeredAt: '2024-06-14',
        isPriority: false,
        questionDate: '2024-06-14',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 305,
        content: '회식 후 여러분의 관계가 어떻게 발전할 것 같으세요?',
        isAnswer: true,
        myAnswer:
          '선배들이랑 진짜 친해져서 나중에 학교생활이나 취업 준비할 때 조언도 많이 얻고 싶어요!',
        answeredAt: '2024-06-15',
        isPriority: false,
        questionDate: '2024-06-15',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 306,
        content: '이 회식을 통해 얻고 싶은 소중한 경험은 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '선배들이랑 진짜 친해져서 나중에 학교생활이나 취업 준비할 때 조언도 많이 얻고 싶어요! 기회가 되면 다음 번 예소나 다른 프로젝트도 같이 나가면 좋을 것 같아요',
        answeredAt: '2024-06-16',
        isPriority: false,
        questionDate: '2024-06-16',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 307,
        content: '회식 후 어떤 기분으로 돌아오고 싶나요? 그 이유는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '진짜 뿌듯하고 행복한 기분으로 돌아오고 싶어요, 다들이랑 친해지고 좋은 추억 만들면 그럴 것 같아요.',
        answeredAt: '2024-06-17',
        isPriority: false,
        questionDate: '2024-06-17',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 308,
        content:
          '이 자리가 여러분의 마음속에 어떤 행복한 기억으로 남길 바라는가요?',
        isAnswer: true,
        myAnswer:
          '다 같이 웃고 떠들면서 술 마시던 그 순간들이 오래오래 기억에 남았으면 좋겠어요!',
        answeredAt: '2024-06-18',
        isPriority: false,
        questionDate: '2024-06-18',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
    ],
  },
  {
    eventId: 3,
    title: '예소 네트워킹 데이',
    emotion: 'HOPE',
    eventStatus: 'termination',
    startDate: '2024-04-15',
    endDate: '2024-05-03',
    memo: '두번째 예소, 두번째 네트워킹!',
    fileUrl: '/image/dummy/hope_flower.png',
    totalQuestionCount: 7,
    totalAnswerCount: 7,
    occurrenceTime: '14:00',
    representativeQuestion: {
      questionId: 403,
      content:
        '이번 네트워킹에서 나누는 대화가 당신에게 어떤 긍정적인 변화를 가져올 것이라 생각하나요?',
      isAnswer: true,
      myAnswer:
        '아무래도 컴공과 사람들이랑 얘기하다 보면 기술적인 부분 이해도 늘고 협업 능력도 좋아질 것 같아요, 진짜 기대돼요!',
      answeredAt: '2024-04-21',
      isPriority: false,
      questionDate: '2024-04-21',
      fileUrl: '',
      type: 'TEXT',
      eventTitle: '예소 네트워킹 데이',
    },
    questionContent: [
      {
        questionId: 401,
        content:
          '예소 네트워킹에서 어떤 특별한 사람을 만나기를 기대하고 있나요?',
        isAnswer: true,
        myAnswer:
          '아, 진짜 코딩 잘하는 컴공과 선배 만나서 우리 디자인팀 아이디어 실현할 수 있게 도와줬으면 좋겠어요!',
        answeredAt: '2024-04-15',
        isPriority: true,
        questionDate: '2024-04-15',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 402,
        content: '어떤 오랜지나 새로운 아이디어를 교류하고 싶으신가요?',
        isAnswer: true,
        myAnswer:
          '음... 제가 생각한 UI/UX 디자인이랑 AI 기술 결합해서 뭔가 신박한 거 만들어보고 싶은데, 어떨까요?',
        answeredAt: '2024-04-18',
        isPriority: false,
        questionDate: '2024-04-18',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 403,
        content:
          '이번 네트워킹에서 나누는 대화가 당신에게 어떤 긍정적인 변화를 가져올 것이라 생각하나요?',
        isAnswer: true,
        myAnswer:
          '아무래도 컴공과 사람들이랑 얘기하다 보면 기술적인 부분 이해도 늘고 협업 능력도 좋아질 것 같아요, 진짜 기대돼요!',
        answeredAt: '2024-04-21',
        isPriority: false,
        questionDate: '2024-04-21',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 404,
        content:
          '이 이벤트에서의 만남을 통해 어떤 꿈이나 목표를 향해 나아가고 싶나요?',
        isAnswer: true,
        myAnswer:
          '제 꿈이 IT 기업에서 UX 디자이너로 일하는 건데, 이번 기회로 기술적인 이해도 높이고 싶어요!',
        answeredAt: '2024-04-24',
        isPriority: false,
        questionDate: '2024-04-24',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 405,
        content:
          '예소 네트워킹에서의 경험이 당신의 아이디어 밴드에 어떤 새로운 색깔을 더할 것이라 기대하나요?',
        isAnswer: true,
        myAnswer:
          '아무래도 기술적인 지식이 늘면 제 디자인 아이디어도 더 현실성 있고 창의적으로 바뀔 것 같아요, 기대돼요!',
        answeredAt: '2024-04-27',
        isPriority: false,
        questionDate: '2024-04-27',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 406,
        content:
          '이번 이벤트를 통해 얻은 인사이트가 어떻게 당신의 향후 계획에 도움을 줄 것이라고 생각하나요?',
        isAnswer: true,
        myAnswer:
          '이번에 배운 거 토대로 포트폴리오에 기술 융합 프로젝트 하나 넣을 수 있으면 좋겠어요, 취업할 때 도움될 것 같아요!',
        answeredAt: '2024-04-30',
        isPriority: false,
        questionDate: '2024-04-30',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 407,
        content:
          '이벤트가 끝난 후, 당신의 마음이 어떻게 변화되어 있을 것이라고 예상하나요?',
        isAnswer: true,
        myAnswer:
          '아마 엄청 뿌듯하고 자신감 넘칠 것 같아요, 새로운 사람들이랑 협업하면서 제 한계를 좀 깨부순 느낌?',
        answeredAt: '2024-05-03',
        isPriority: false,
        questionDate: '2024-05-03',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
    ],
  },
];

export const mockAllEventList: MonthAllEventsType[] = [
  {
    groupByDate: '2024-07',
    questionContent: [
      {
        questionId: 217,
        content:
          '중간 발표를 통해 더 크게 도약할 수 있을 것 같은 순간은 어떤 때인가요?',
        isAnswer: true,
        myAnswer:
          '발표 끝나고 교수님들이 우리 아이디어에 조언해주실 때요, 그때 진짜 프로젝트가 더 발전할 수 있을 것 같아요.',
        isPriority: false,
        questionDate: '2024-07-02',
        answeredAt: '2024-07-02',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 218,
        content: '발표 준비 과정에서 가장 기억에 남는 에피소드는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '첫 회의 때 의견 충돌 있었는데 그러다가 오히려 더 좋은 아이디어가 나왔던 거요, 지금 생각하면 그게 제일 기억에 남아요.',
        isPriority: false,
        questionDate: '2024-07-04',
        answeredAt: '2024-07-04',
        fileUrl:
          'https://daydreamcdn.s3.ap-northeast-2.amazonaws.com/DayDream/dummy/KakaoTalk_Photo_2024-10-04-01-10-27.jpeg',
        type: 'IMAGE',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 219,
        content: '이 아이디어에 대한 사랑이 더욱 깊어지는 순간은 언제인가요?',
        isAnswer: true,
        myAnswer:
          '우리 아이디어로 실제로 누군가의 삶이 더 즐거워질 수 있겠다고 생각할 때마다 더 애착이 가요.',
        isPriority: false,
        questionDate: '2024-07-06',
        answeredAt: '2024-07-06',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 220,
        content: '발표 직후 느낄 화려한 감정은 어떤 모습일까요?',
        isAnswer: true,
        myAnswer:
          '아마 뿌듯하면서도 약간은 안도감이 들 것 같아요, 첫 관문 통과한 느낌?',
        isPriority: false,
        questionDate: '2024-07-08',
        answeredAt: '2024-07-08',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 221,
        content:
          '이번 중간 발표가 끝난 후 가장 큰 기대감으로 남을 것은 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '이번 중간 발표를 통해 받은 피드백으로 우리 아이디어를 더 발전시켜서 최종 발표 때 수상을 할 수 있지 않을까 하는 기대감이요!',
        isPriority: false,
        questionDate: '2024-07-10',
        answeredAt: '2024-07-10',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
    ],
  },
  {
    groupByDate: '2024-06',
    questionContent: [
      {
        questionId: 201,
        content: '이번 중간 발표에서 가장 기대하고 있는 부분은 어떤 건가요?',
        isAnswer: true,
        myAnswer:
          '다른 팀들이 어떤 주제로 프로젝트 하는지 너무 궁금해요, 우리 아이디어랑 비교해보고 싶어요!',
        isPriority: true,
        questionDate: '2024-05-30',
        answeredAt: '2024-05-30',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 202,
        content: '발표를 통해 전하고 싶은 메시지는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '우리 팀이 고민한 주제의 중요성이랑 의미가 잘 전달됐으면 좋겠어요, 특히 기다림에 대한 예술적 표현이랑 그걸 기술적으로 융합한 부분요.',
        isPriority: false,
        questionDate: '2024-06-01',
        answeredAt: '2024-06-01',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 203,
        content: '중간 발표를 통해 어떤 피드백을 받고 싶으신가요?',
        isAnswer: true,
        myAnswer:
          '교수님들이 우리 아이디어 방향성에 대해 조언 좀 해주셨으면 좋겠어요, 아직 초기 단계라 도움이 필요해요.',
        isPriority: false,
        questionDate: '2024-06-03',
        answeredAt: '2024-06-03',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 204,
        content: '발표 전 준비하면서 가장 설렜던 순간은 언제였나요?',
        isAnswer: true,
        myAnswer:
          '팀원들이랑 처음으로 아이디어 회의할 때였어요. 다들 열정적으로 의견 내는 모습 보고 앞으로의 프로젝트가 어떨지 설렜어요!',
        isPriority: false,
        questionDate: '2024-06-05',
        answeredAt: '2024-06-05',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 205,
        content:
          '이번 중간 발표에서 팀원들과의 협력이 어떤 의미를 가지길 바라나요?',
        isAnswer: true,
        myAnswer:
          '컴공과랑 디자인과가 만나서 서로 다른 시각으로 문제 해결하는 게 잘 드러났으면 좋겠어요.',
        isPriority: false,
        questionDate: '2024-06-07',
        answeredAt: '2024-06-07',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 206,
        content: '발표 후 어떤 성취감을 느끼고 싶으신가요?',
        isAnswer: true,
        myAnswer:
          '우리 아이디어가 다른 팀들이나 교수님들께 좋은 인상을 남겼으면 좋겠어요. 주제에 대해 고민을 많이 했는데 그것에 대한 좋은 평가를 받고 싶어요!',
        isPriority: false,
        questionDate: '2024-06-09',
        answeredAt: '2024-06-09',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 207,
        content: '이 아이디어에 대한 남다른 열정을 느끼는 순간은 언제인가요?',
        isAnswer: true,
        myAnswer:
          '밤늦게까지 아이디어 회의하다가 갑자기 와, 이거 진짜 대박일 수도? 하는 생각이 들 때 열정 불타요.',
        isPriority: false,
        questionDate: '2024-06-11',
        answeredAt: '2024-06-11',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 208,
        content: '중간 발표에서 청중의 반응을 어떻게 느끼길 기대하나요?',
        isAnswer: true,
        myAnswer:
          '발표할 때 다른 팀들이 우리 아이디어에 관심 보이면서 질문 많이 해줬으면 좋겠어요!',
        isPriority: false,
        questionDate: '2024-06-13',
        answeredAt: '2024-06-13',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 209,
        content:
          '이번 발표 때문에 밤잠을 설쳐본 경험이 있다면 그건 어떤 기분이었나요?',
        isAnswer: true,
        myAnswer:
          '비대면이라 긴장은 덜 한데, 그래도 잘 전달될까 걱정되는 마음에 좀 설레요.',
        isPriority: false,
        questionDate: '2024-06-15',
        answeredAt: '2024-06-15',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 210,
        content: '발표가 끝난 후 가장 먼저 하고 싶은 일은 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '팀원들이랑 화상으로 모여서 치맥하면서 수고했다고 말해주고 싶어요, 다들 아이디어 내느라 고생했거든요.',
        isPriority: false,
        questionDate: '2024-06-17',
        answeredAt: '2024-06-17',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 중간발표!',
      },
      {
        questionId: 301,
        content: '이번 회식에서 어떤 특별한 순간을 기대하고 있나요?',
        isAnswer: true,
        myAnswer:
          '아, 진짜 기대되는 건 선배들이랑 처음으로 술 마시는 거? 엄청 떨리긴 한데 재밌을 것 같아요!',
        isPriority: true,
        questionDate: '2024-06-11',
        answeredAt: '2024-06-11',
        fileUrl: 'https://example.com/team-dinner-expectations.jpg',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 302,
        content:
          '팀원들과 나누고 싶은 가장 재밌는 이야기나 에피소드는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '음...술 마시는 자리니까 술 마시고 생긴 웃긴얘기를 풀면 될 것 같아요. 그냥 제가 MT 갔다가 술 마시고 화장실 못 찾아서 헤맨 얘기 하면 다들 웃겠죠?',
        isPriority: false,
        questionDate: '2024-06-12',
        answeredAt: '2024-06-12',
        fileUrl: 'https://example.com/funny-story-audio.mp3',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 303,
        content: '회식에서 어떤 음식을 가장 기대하고 있나요?',
        isAnswer: true,
        myAnswer:
          '진짜 삼겹살이랑 소주 콤보가 최고인 것 같아요, 근데 회식이라 좀 비싼 거 먹을 수 있을까 봐 기대돼요!',
        isPriority: false,
        questionDate: '2024-06-13',
        answeredAt: '2024-06-13',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 304,
        content:
          '팀원들과의 첫 만남 이후 서로에 대한 인상이 어떻게 바뀌었나요?',
        isAnswer: true,
        myAnswer:
          '아무래도 술 마시고 얘기 많이 하면 더 친해질 것 같은데... 제가 실수하면 어쩌죠?',
        isPriority: false,
        questionDate: '2024-06-14',
        answeredAt: '2024-06-14',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 305,
        content: '회식 후 여러분의 관계가 어떻게 발전할 것 같으세요?',
        isAnswer: true,
        myAnswer:
          '선배들이랑 진짜 친해져서 나중에 학교생활이나 취업 준비할 때 조언도 많이 얻고 싶어요!',
        isPriority: false,
        questionDate: '2024-06-15',
        answeredAt: '2024-06-15',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 306,
        content: '이 회식을 통해 얻고 싶은 소중한 경험은 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '선배들이랑 진짜 친해져서 나중에 학교생활이나 취업 준비할 때 조언도 많이 얻고 싶어요! 기회가 되면 다음 번 예소나 다른 프로젝트도 같이 나가면 좋을 것 같아요',
        isPriority: false,
        questionDate: '2024-06-16',
        answeredAt: '2024-06-16',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 307,
        content: '회식 후 어떤 기분으로 돌아오고 싶나요? 그 이유는 무엇인가요?',
        isAnswer: true,
        myAnswer:
          '진짜 뿌듯하고 행복한 기분으로 돌아오고 싶어요, 다들이랑 친해지고 좋은 추억 만들면 그럴 것 같아요.',
        isPriority: false,
        questionDate: '2024-06-17',
        answeredAt: '2024-06-17',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
      {
        questionId: 308,
        content:
          '이 자리가 여러분의 마음속에 어떤 행복한 기억으로 남길 바라는가요?',
        isAnswer: true,
        myAnswer:
          '다 같이 웃고 떠들면서 술 마시던 그 순간들이 오래오래 기억에 남았으면 좋겠어요!',
        isPriority: false,
        questionDate: '2024-06-18',
        answeredAt: '2024-06-18',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '팀 d!no 회식🌼',
      },
    ],
  },
  {
    groupByDate: '2024-05',
    questionContent: [
      {
        questionId: 405,
        content:
          '예소 네트워킹에서의 경험이 당신의 아이디어 밴드에 어떤 새로운 색깔을 더할 것이라 기대하나요?',
        isAnswer: true,
        myAnswer:
          '아무래도 기술적인 지식이 늘면 제 디자인 아이디어도 더 현실성 있고 창의적으로 바뀔 것 같아요, 기대돼요!',
        isPriority: false,
        questionDate: '2024-04-27',
        answeredAt: '2024-04-27',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 406,
        content:
          '이번 이벤트를 통해 얻은 인사이트가 어떻게 당신의 향후 계획에 도움을 줄 것이라고 생각하나요?',
        isAnswer: true,
        myAnswer:
          '이번에 배운 거 토대로 포트폴리오에 기술 융합 프로젝트 하나 넣을 수 있으면 좋겠어요, 취업할 때 도움될 것 같아요!',
        isPriority: false,
        questionDate: '2024-04-30',
        answeredAt: '2024-04-30',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 407,
        content:
          '이벤트가 끝난 후, 당신의 마음이 어떻게 변화되어 있을 것이라고 예상하나요?',
        isAnswer: true,
        myAnswer:
          '아마 엄청 뿌듯하고 자신감 넘칠 것 같아요, 새로운 사람들이랑 협업하면서 제 한계를 좀 깨부순 느낌?',
        isPriority: false,
        questionDate: '2024-05-03',
        answeredAt: '2024-05-03',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
    ],
  },
  {
    groupByDate: '2024-04',
    questionContent: [
      {
        questionId: 401,
        content:
          '예소 네트워킹에서 어떤 특별한 사람을 만나기를 기대하고 있나요?',
        isAnswer: true,
        myAnswer:
          '아, 진짜 코딩 잘하는 컴공과 선배 만나서 우리 디자인팀 아이디어 실현할 수 있게 도와줬으면 좋겠어요!',
        isPriority: true,
        questionDate: '2024-04-15',
        answeredAt: '2024-04-15',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 402,
        content: '어떤 오랜지나 새로운 아이디어를 교류하고 싶으신가요?',
        isAnswer: true,
        myAnswer:
          '음... 제가 생각한 UI/UX 디자인이랑 AI 기술 결합해서 뭔가 신박한 거 만들어보고 싶은데, 어떨까요?',
        isPriority: false,
        questionDate: '2024-04-18',
        answeredAt: '2024-04-18',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 403,
        content:
          '이번 네트워킹에서 나누는 대화가 당신에게 어떤 긍정적인 변화를 가져올 것이라 생각하나요?',
        isAnswer: true,
        myAnswer:
          '아무래도 컴공과 사람들이랑 얘기하다 보면 기술적인 부분 이해도 늘고 협업 능력도 좋아질 것 같아요, 진짜 기대돼요!',
        isPriority: false,
        questionDate: '2024-04-21',
        answeredAt: '2024-04-21',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
      {
        questionId: 404,
        content:
          '이 이벤트에서의 만남을 통해 어떤 꿈이나 목표를 향해 나아가고 싶나요?',
        isAnswer: true,
        myAnswer:
          '제 꿈이 IT 기업에서 UX 디자이너로 일하는 건데, 이번 기회로 기술적인 이해도 높이고 싶어요!',
        isPriority: false,
        questionDate: '2024-04-24',
        answeredAt: '2024-04-24',
        fileUrl: '',
        type: 'TEXT',
        eventTitle: '예소 네트워킹 데이',
      },
    ],
  },
];
